{
 "title": "MikroTik SNMP",
 "description": "Mikrotik snmp monitoring (prometheus)",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp v3",
  "snmp_exporter"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets,  instance)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_name",
    "query": {
     "query": "query_result((mtxrQueueTreePackets * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_parent",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_flow",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeName) group_left(mtxrQueueTreeIndex) mtxrQueueTreeIndex{instance='$instance',}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SNMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total SNMP time",
     "type": "stat",
     "description": "Total SNMP time scrape took (walk and processing)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_duration_seconds{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Time SNMP walk",
     "type": "stat",
     "description": "Time SNMP walk/bulkwalk took",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_walk_duration_seconds{instance='$instance'}"
      }
     ]
    },
    {
     "title": "PDUs returned",
     "type": "stat",
     "description": "PDUs returned from walk",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_pdus_returned{instance='$instance'}"
      }
     ]
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorTemperature{instance='$instance'}/10 or mtxrHlTemperature{instance='$instance'}/10"
    }
   ]
  },
  {
   "title": "Load RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Load system disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})",
     "legendFormat": "Load CPU {{hrDeviceIndex}} "
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "System disk"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "RouterOS date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(hrSystemDate{instance='$instance'})"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrLicVersion{instance='$instance'}",
     "legendFormat": "{{mtxrLicVersion}}"
    }
   ]
  },
  {
   "title": "Board ver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrFirmwareVersion{instance='$instance'}",
     "legendFormat": "{{mtxrFirmwareVersion}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Status device",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceStatus{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "POE Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEStatus{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The number of errors detected on this device",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceErrors{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "stat",
   "description": "DHCP Lease Count",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrDHCPLeaseCount{instance='$instance'}"
    }
   ]
  },
  {
   "title": "CPU Mhz",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorFrequency{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    { "expr": "ifSpeed{instance='$instance'}" },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance='$instance'}"
    },
    { "expr": "ifMtu{instance='$instance'}" },
    {
     "expr": "ifType_info{instance='$instance'}"
    },
    {
     "expr": "mtxrPOEInterfaceIndex{instance='$instance'}"
    },
    { "expr": "ifAlias{instance='$instance'}" }
   ]
  },
  {
   "title": "Neighbors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mtxrNeighborInterfaceID{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborIdentity{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborIpAddress{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborMacAddress{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborPlatform{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborSoftwareID{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborVersion{instance='$instance'}"
    }
   ]
  },
  { "title": "Interfaces Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Traffic \"$Interface\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Multicast / Unicast / Errors etc.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
     "repeat": "Interface",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Rx Eth errors, etc",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(mtxrInterfaceStatsRxAlignError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Align Error - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxCarrierError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Carrier Error - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxControl{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Control - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxDrop{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Drop - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxFCSError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "FCS Error - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxFragment{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Fragment - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxJabber{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Jabber - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxLengthError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Length Error - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxOverflow{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Overflow - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxPause{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Pause - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxTooLong{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Too Long - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxTooShort{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Too Short - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsRxUnknownOp{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Rx Unknown Op - {{ifName}}"
      }
     ]
    },
    {
     "title": "Tx Eth errors, etc",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(mtxrInterfaceStatsTxControl{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Control - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxDeferred{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Deferred - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Collision - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxDrop{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Drop - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxExcessiveCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Excessive Collision - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxExcessiveDeferred{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Excessive Deferred - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxFCSError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx FCS Error - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxFragment{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Fragment - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxJabber{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Jabber - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxLateCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Late Collision - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxMultipleCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Multiple Collision - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxPause{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Pause - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxPauseHonored{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Pause Honored - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxSingleCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Single Collision - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxTooLong{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Too Long - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxTooShort{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Too Short - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxTotalCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Total Collision - {{ifName}}"
      },
      {
       "expr": "irate(mtxrInterfaceStatsTxUnderrun{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Tx Under run - {{ifName}}"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "graph",
     "description": "Maximum Transmission Unit",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "MTU", "label": "Maximum Transmission Unit" }
     ],
     "targets": [
      { "expr": "ifMtu{instance='$instance'}", "legendFormat": "{{ifName}}" }
     ]
    },
    {
     "title": "POE Power",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrPOEPower{instance='$instance'}",
       "legendFormat": "POE Power"
      }
     ]
    },
    {
     "title": "POE Voltage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrPOEVoltage{instance='$instance'}",
       "legendFormat": "POE Voltage"
      }
     ]
    },
    {
     "title": "POE Current",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrPOECurrent{instance='$instance'}",
       "legendFormat": "POE Current"
      }
     ]
    },
    {
     "title": "CAPsMAN client count",
     "type": "stat",
     "description": "Wireless registration table entry count",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWlCMRtabEntryCount{instance='$instance'}"
      }
     ]
    },
    {
     "title": "CPU Temp",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mtxrHlTemperature{instance='$instance'}/10",
       "legendFormat": "CPU Temp"
      }
     ]
    },
    {
     "title": "Serial Number",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 116 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrSerialNumber{instance='$instance'}",
       "legendFormat": "{{mtxrSerialNumber}}"
      }
     ]
    },
    {
     "title": "Software ID",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 116 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrLicSoftwareId{instance='$instance'}",
       "legendFormat": "{{mtxrLicSoftwareId}}"
      }
     ]
    },
    {
     "title": "Wi-Fi client count",
     "type": "stat",
     "description": "Wireless registration table entry count",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 116 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWlRtabEntryCount{instance='$instance'}"
      }
     ]
    }
   ]
  }
 ]
}