global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#test-channel"
        text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
