{
 "title": "Backend - TV",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(5, rate(mysql_global_status_commands_total[5m]) > 0) or topk(5, irate(mysql_global_status_commands_total[5m]) > 0)) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "MySQL slow queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "slow queries / s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[5m]) or irate(mysql_global_status_slow_queries[5m])",
     "legendFormat": "{{instance}} 5m"
    },
    {
     "expr": "rate(mysql_global_status_slow_queries[1m]) or irate(mysql_global_status_slow_queries[1m])",
     "legendFormat": "{{instance}} 1m"
    }
   ]
  },
  {
   "title": "Average WMS response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(nginxlog_http_response_time_seconds_sum{logfile=\"/home/www/zoot.cz/_log/nginx/wms-api-zoot.cz.access.gw.log\"})",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Documents indexed per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Documents / sec" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total[5m])",
     "legendFormat": "Server name: {{name}}"
    }
   ]
  },
  {
   "title": "Rabbit queues/messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_queue_messages) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Rabbit Queue ack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Ack messages / sec" }
   ],
   "targets": [
    {
     "expr": "max(rate(rabbitmq_queue_messages_ack_total[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Cluster health",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{color=\"red\"})==1 or (max(elasticsearch_cluster_health_status{color=\"green\"})==1)+4 or (max(elasticsearch_cluster_health_status{color=\"yellow\"})==1)+22"
    }
   ]
  },
  {
   "title": "bas-1 HTTP codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{instance=~\"zoot-bas-1.*\", cfg=\"/etc/nginx/sites-enabled/zoot.cz\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "bas-2 HTTP codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{instance=~\"zoot-bas-2.*\", cfg=\"/etc/nginx/sites-enabled/zoot.cz\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "bas-3 HTTP codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{instance=~\"zoot-bas-3.*\", cfg=\"/etc/nginx/sites-enabled/zoot.cz\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "bas-4 HTTP codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{instance=~\"zoot-bas-4.*\", cfg=\"/etc/nginx/sites-enabled/zoot.cz\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  }
 ]
}