version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/prometheus/etc/prometheus:/etc/prometheus"
      - "$PWD/prometheus/data:/prometheus"
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "$PWD/alertmanager/etc/alertmanager:/etc/alertmanager"
      - "$PWD/alertmanager/data:/alertmanager"
    restart: always

  grafana:
    image: grafana/grafana
    volumes:
      - "$PWD/grafana/data:/var/lib/grafana"
    expose:
      - "3000"
    restart: always

networks:
  default:
    external: true
    name: prometheus
