services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/data:/prometheus"
    restart: always

  alertmanager:
    build:
      context: ./alertmanager
      dockerfile: Dockerfile
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager/data:/alertmanager"
    restart: always

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    volumes:
      - "./grafana/data:/var/lib/grafana"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - prometheus
      - nginx-proxy

  pushgateway:
    build:
      context: ./pushgateway
      dockerfile: Dockerfile
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: always

  node_exporter:
    build:
      context: ./node_exporter
      dockerfile: Dockerfile
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    expose:
      - 9100

  snmp-exporter:
    build:
      context: ./snmp-exporter
      dockerfile: Dockerfile
    container_name: snmp-exporter
    expose:
      - "9116"
#    volumes:
#      - "./snmp-exporter:/etc/snmp-exporter"
    restart: always

networks:
  prometheus:
    name: prometheus
    external: false
  nginx-proxy:
    external: true
