version: "3.3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/prometheus/etc/prometheus:/etc/prometheus"
      - "$PWD/prometheus/data:/prometheus"
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "$PWD/alertmanager/etc/alertmanager:/etc/alertmanager"
      - "$PWD/alertmanager/data:/alertmanager"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - "$PWD/grafana/data:/var/lib/grafana"
    ports:
      - "3000:3000"
    restart: always

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
#    network_mode: host
#    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    expose:
      - 9100

  snmp-exporter:
    image: quay.io/prometheus/snmp-exporter
    container_name: snmp-exporter
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
#    expose:
#      - 9116
    ports:
      - 9116:9116
    restart: always

#  snmp:
#    image: quay.io/prometheus/snmp-exporter
#    container_name: snmp-exporter
#    volumes:
#      - "$PWD/data:/etc/snmp_exporter"
#    ports:
#      - 9116:9116
#      - 116:116/udp
#    restart: always
#    command: --config.file=/etc/snmp_exporter/snmp.yml

#  pushgateway:
#    image: prom/pushgateway
#    container_name: pushgateway
#    ports:
#      - "9091:9091"
#    restart: always

#networks:
#  default:
#    external: true
#    name: prometheus
