{
 "title": "Frontend - TV",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "zoot.cz - HTTP codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Reqs per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.cz\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "zoot.sk - HTTP codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Reqs per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.sk\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "zoot.ro - HTTP codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Reqs per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.ro\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "zoot.cz/api - HTTP codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Reqs per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{logfile=\"/home/www/zoot.cz/_log/nginx/api-zoot.cz.access.gw.log\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "zoot.cz - response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_time_seconds_sum{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.cz\", logfile!=\"/home/www/zoot.cz/_log/nginx/api-zoot.cz.access.gw.log\"}[5m])) by (logfile) / sum(rate(nginxlog_http_response_time_seconds_count{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.cz\"}[5m])) by (logfile)"
    }
   ]
  },
  {
   "title": "zoot.sk - response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_time_seconds_sum{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.sk\"}[5m])) by (logfile) / sum(rate(nginxlog_http_response_time_seconds_count{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.sk\"}[5m])) by (logfile)"
    }
   ]
  },
  {
   "title": "zoot.ro - response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_time_seconds_sum{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.ro\"}[5m])) by (logfile) / sum(rate(nginxlog_http_response_time_seconds_count{instance=~\"zoot-lb-.*\", cfg=\"/etc/nginx/sites-enabled/zoot.ro\"}[5m])) by (logfile)"
    }
   ]
  },
  {
   "title": "zoot.cz/api - response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_time_seconds_sum{logfile=\"/home/www/zoot.cz/_log/nginx/api-zoot.cz.access.gw.log\"}[5m])) by (logfile) / sum(rate(nginxlog_http_response_time_seconds_count{logfile=\"/home/www/zoot.cz/_log/nginx/api-zoot.cz.access.gw.log\"}[5m])) by (logfile)"
    }
   ]
  },
  {
   "title": "Cluster health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{color=\"red\"})==1 or (max(elasticsearch_cluster_health_status{color=\"green\"})==1)+4 or (max(elasticsearch_cluster_health_status{color=\"yellow\"})==1)+22"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_process_cpu_percent) / count(elasticsearch_process_cpu_percent)"
    }
   ]
  },
  {
   "title": "ES - query time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "ES - documents indexed rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "index calls per second" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "ES - indexed documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "elasticsearch_indices_docs", "legendFormat": "Server: {{name}}" }
   ]
  },
  {
   "title": "Redis - reqs / min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=~\"zoot-fas-.*\", cmd=\"get\"}[1m]))*60",
     "legendFormat": "Get requests per minute."
    },
    {
     "expr": "sum(rate(redis_commands_total{instance=~\"zoot-fas-.*\"}[1m]))*60",
     "legendFormat": "All requests per minute."
    }
   ]
  },
  {
   "title": "Redis - response times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance=~\"zoot-fas-.*\", cmd=\"get\"}[1m]))*60",
     "legendFormat": "Response time of GET commands."
    },
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance=~\"zoot-fas-.*\"}[1m]))*60",
     "legendFormat": "Response time of all commands."
    }
   ]
  },
  {
   "title": "Redis - total number of keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=~\"zoot-fas.*\"}) by (instance)",
     "legendFormat": "Total by Fas {{ instance }}"
    }
   ]
  }
 ]
}