variables:
  ACME_COMPANION_COMPONENT: "acme-companion"
  ACME_COMPANION_VERSION: "1.0" # If you change the builder, bump the version here
  # This variable is also set by the kaniko image based on provided COMPONENT and VERSION
  # If these match, and an image is built in the pipeline, the sha digest is used instead in scripts
  # this has no effect on gitlab job definitions (image:xyz) though as these are resolved before any scripts are run
  ACME_COMPANION_IMAGE: "$CI_REGISTRY_IMAGE/$ACME_COMPANION_COMPONENT:$ACME_COMPANION_VERSION"
  
acme-companion-build:
  extends: .kaniko-build-template
  stage: .pre
  variables:
    COMPONENT: $ACME_COMPANION_COMPONENT
    CONTEXT: "acme-companion"
    DOCKERFILE: "acme-companion/Dockerfile"
  only:
    changes:
      - acme-companion/**/*
